### ISSUE TITLE
Use of defines in reproducible builds

### ISSUE THREAD

**Issue by RobTillaart** [arduino/tooling-rfcs#9]
Often builds have command line defines

As these defines are part of the build they must be includable in the profile. e.g.
```
profiles:
  nanorp:
    fqbn: arduino:mbed_nano:nanorp2040connect
    platforms:
      - platform: arduino:mbed_nano (2.1.0)
    libraries:
      - ArduinoIoTCloud (1.0.2)
    defines:
      - SIZE: 128
  
  other:
    fqbn: ...
    platforms:
      - platform: ....
    libraries:
      - ....
    defines:
      - SIZE: 64
```

If the user defines the define on the command line, it overrules the value in the profile

```
arduino-cli compile [sketch] --DSIZE=256--profile myProject
```
